import { Province, Relation, Economy, Position, PLAYER_HOUSE } from '../components/index.js'
export class DiplomacySystem{
  reads=new Set([Province, Relation, Economy, Position]); writes=new Set([Relation]); phase='ai'
  update(world, events, dt){
    const houses=new Set(); const count=new Map(); const fiefsByHouse=new Map()
    for(const[,[pos,fief]] of world.query(Position, Province)){ houses.add(fief.ownerId); count.set(fief.ownerId,(count.get(fief.ownerId)||0)+1); if(!fiefsByHouse.has(fief.ownerId)) fiefsByHouse.set(fief.ownerId,[]); fiefsByHouse.get(fief.ownerId).push(pos.provinceId) }
    const coffers=new Map(); for(const[,[c]] of world.query(Economy)) coffers.set(c.ownerId,{gold:c.gold,unrest:c.warExhaustion||0})
    const ids=[...houses]; if(ids.length<2) return
    const opinion=new Map()
    for(const[eid,[rel]] of world.query(Relation)){ if(rel.ownerId==null) continue; if(rel.warScore==null) rel.warScore=0; opinion.set(`${rel.ownerId}->${rel.targetId}`,{eid,rel}) }
    for(const a of ids){ for(const b of ids){ if(a===b) continue; const k=`${a}->${b}`; if(!opinion.has(k)){ const eid=world.createEntity(); const r=new Relation(b,0,a,0); world.addComponent(eid,r); opinion.set(k,{eid,rel:r}) } } }
    // player intents
    for(const d of events.drain('player_declare_war')){ const target=d.target; if(target===PLAYER_HOUSE) continue; const k1=`${PLAYER_HOUSE}->${target}`, k2=`${target}->${PLAYER_HOUSE}`; if(opinion.has(k1)){ opinion.get(k1).rel.value=-100; opinion.get(k1).rel.warScore=Math.max(opinion.get(k1).rel.warScore,5) } if(opinion.has(k2)){ opinion.get(k2).rel.value=-100; opinion.get(k2).rel.warScore=Math.min(opinion.get(k2).rel.warScore,-5) } events.emit('oath_broken',{from:PLAYER_HOUSE,to:target,byPlayer:true}); events.emit('war_declared',{from:PLAYER_HOUSE,to:target}) }
    for(const dem of events.drain('player_demand_tribute')){ const target=dem.target; const k=`${PLAYER_HOUSE}->${target}`; const rel=opinion.get(k)?.rel; const warScore=rel?.warScore||0; const targetGold=coffers.get(target)?.gold||0; if(warScore<25){ events.emit('demand_rejected',{from:PLAYER_HOUSE,to:target,reason:'warScore too low',warScore}); continue } const ask=Math.min(dem.gold||Math.floor(warScore*3.6+34), Math.floor(targetGold*0.58)); if(ask<12){ events.emit('demand_rejected',{from:PLAYER_HOUSE,to:target,reason:'target broke'}); continue } const unrest=coffers.get(target)?.unrest||0; const chance = warScore>=55?0.92:warScore>=35?0.74+unrest*0.003:0.48; if(Math.random()<chance){ events.emit('tribute_demand',{from:target,to:PLAYER_HOUSE,gold:ask,byPlayer:true}); if(rel) rel.value=Math.max(-100,rel.value-12); events.emit('demand_accepted',{from:PLAYER_HOUSE,to:target,gold:ask,warScore}) } else { events.emit('demand_rejected',{from:PLAYER_HOUSE,to:target,reason:'defiant',warScore}); if(rel){ rel.value=Math.max(-100,rel.value-18); rel.warScore=Math.max(-100,rel.warScore-8) } } }
    for(const req of events.drain('player_sue_peace')){ const target=req.target; const k1=`${PLAYER_HOUSE}->${target}`, k2=`${target}->${PLAYER_HOUSE}`; const rel1=opinion.get(k1)?.rel, rel2=opinion.get(k2)?.rel; const warScore=rel1?.warScore||0; const playerExh=coffers.get(PLAYER_HOUSE)?.unrest||0, targetExh=coffers.get(target)?.unrest||0, avg=(playerExh+targetExh)/2; const isWinning=warScore>=0; let gold=0, provs=[]; if(isWinning){ gold=warScore>=30?Math.floor(warScore*3.3+28):0; if(warScore>=60){ const foeFiefs=fiefsByHouse.get(target)||[]; if(foeFiefs.length) provs=[foeFiefs[0]] } if(Math.random()< (warScore>=50?0.95:warScore>=20?0.86:0.76)){ if(rel1){rel1.value=34+Math.random()*12; rel1.warScore=0} if(rel2){rel2.value=34+Math.random()*12; rel2.warScore=0} events.emit('peace_treaty',{winner:PLAYER_HOUSE,loser:target,warScore,demands:{gold,provinces:provs},byPlayer:true}); events.emit('peace_accepted',{from:target,to:PLAYER_HOUSE,warScore,gold,provs}) } else { events.emit('peace_rejected',{from:target,to:PLAYER_HOUSE,warScore,reason:'still defiant'}) } } else { const loseScore=-warScore; gold=Math.floor(loseScore*2.9+34+avg*0.6); if(loseScore>55){ const myFiefs=fiefsByHouse.get(PLAYER_HOUSE)||[]; if(myFiefs.length>1) provs=[myFiefs[0]] } if(Math.random()<0.80){ if(rel1){rel1.value=30+Math.random()*10; rel1.warScore=0} if(rel2){rel2.value=30+Math.random()*10; rel2.warScore=0} events.emit('peace_treaty',{winner:target,loser:PLAYER_HOUSE,warScore:loseScore,demands:{gold,provinces:provs},byPlayer:true}); events.emit('peace_accepted',{from:PLAYER_HOUSE,to:target,asLoser:true,gold,provs,warScore}) } else { events.emit('peace_rejected',{from:target,to:PLAYER_HOUSE,warScore,reason:'offer too low'}) } } }
    for(const bw of events.drain('battle_won')){ const w=bw.winner, ls=bw.losers||[], g=bw.warScoreGain||14; for(const l of ls){ const k1=`${w}->${l}`,k2=`${l}->${w}`; if(opinion.has(k1)) opinion.get(k1).rel.warScore=Math.min(100,opinion.get(k1).rel.warScore+g); if(opinion.has(k2)) opinion.get(k2).rel.warScore=Math.max(-100,opinion.get(k2).rel.warScore-g) } }
    for(const s of events.drain('fief_seized')){ const w=s.to,l=s.from; const k1=`${w}->${l}`,k2=`${l}->${w}`; if(opinion.has(k1)) opinion.get(k1).rel.warScore=Math.min(100,opinion.get(k1).rel.warScore+26); if(opinion.has(k2)) opinion.get(k2).rel.warScore=Math.max(-100,opinion.get(k2).rel.warScore-26) }
    for(const {rel} of opinion.values()){ if(rel.ownerId===PLAYER_HOUSE) continue; const unrestA=coffers.get(rel.ownerId)?.unrest||0, unrestB=coffers.get(rel.targetId)?.unrest||0, avg=(unrestA+unrestB)/2; rel.value+=(Math.random()-0.5)*1.22*dt; if((count.get(rel.ownerId)||1)>5 && (count.get(rel.targetId)||1)>5) rel.value-=0.21*dt; if(rel.value<=-18){ rel.value+=avg*0.03*dt; if(unrestA>64||unrestB>64) rel.value+=1.0*dt } const abs=Math.abs(rel.warScore), winning=rel.warScore>0; if(rel.value<=-12 && abs>=46 && avg>=36 && Math.random()<0.055){ const victor=winning?rel.ownerId:rel.targetId, vanq=winning?rel.targetId:rel.ownerId; const score=winning?rel.warScore:-rel.warScore; const foeFiefs=fiefsByHouse.get(vanq)||[]; const demandN=score>74?2:1; const demanded=foeFiefs.slice(0,demandN); const goldAsk=Math.floor(score*2.9+avg*1.0); const foeGold=coffers.get(vanq)?.gold||0, finalGold=Math.min(goldAsk, Math.floor(foeGold*0.57)); rel.value=36+Math.random()*14; const mirror=`${rel.targetId}->${rel.ownerId}`; if(opinion.has(mirror)){ opinion.get(mirror).rel.value=rel.value; opinion.get(mirror).rel.warScore=0 } rel.warScore=0; events.emit('peace_treaty',{winner:victor,loser:vanq,warScore:score,demands:{gold:finalGold,provinces:demanded}}) } else if(rel.value<=-10 && (unrestA>86||unrestB>86) && Math.random()<0.05){ rel.value=32+Math.random()*16; rel.warScore=0; events.emit('truce_forced',{from:rel.ownerId,to:rel.targetId}) } else { if(rel.value<=-70&&Math.random()<0.012&&rel.value!==-100){ rel.value=-100; rel.warScore=Math.max(rel.warScore,5); events.emit('oath_broken',{from:rel.ownerId,to:rel.targetId}) } if(rel.value>=56&&Math.random()<0.016){ rel.warScore=0; events.emit('peace_sworn',{from:rel.ownerId,to:rel.targetId}) } } rel.value=Math.max(-100,Math.min(100,rel.value)); rel.warScore=Math.max(-100,Math.min(100,rel.warScore)) }
  }
}
